-- Phase 11.5 Risk auto-nudges

ALTER TYPE "NudgeType" ADD VALUE IF NOT EXISTS 'RISK_INVOICE_OVERDUE';
ALTER TYPE "NudgeType" ADD VALUE IF NOT EXISTS 'RISK_INVOICE_HIGH_AMOUNT_UNPAID';
ALTER TYPE "NudgeType" ADD VALUE IF NOT EXISTS 'RISK_WORK_OVERDUE';
ALTER TYPE "NudgeType" ADD VALUE IF NOT EXISTS 'RISK_WORK_BLOCKED';
ALTER TYPE "NudgeType" ADD VALUE IF NOT EXISTS 'RISK_INCIDENT_OPEN';
ALTER TYPE "NudgeType" ADD VALUE IF NOT EXISTS 'RISK_DEAL_STALLED';

ALTER TABLE "nudges"
  ADD COLUMN IF NOT EXISTS "unique_key" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "nudges_unique_key_key"
  ON "nudges"("unique_key");
